CREATE TABLE IF NOT EXISTS todos_user(
    id SERIAL PRIMARY KEY INT, 
    title VARCHAR(255) NOT NULL, 
    completed: BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
;